#!/usr/bin/env bash
#Bash script that groups visitors by IP and HTTP status code, and displays this data.
logfile="apache-access.log"

awk '{ ip[$1$9]++ } END { for (i in ip) print ip[i], substr(i, 1, length(i)-3), substr(i, length(i)-2) }' "$logfile" | sort -rn
