#!/usr/bin/env bash
# Specify the path to your Apache log file
LOG_FILE="/path/to/apache.log"

# Use awk to process the log file
awk '{ count[$1" "$9]++ } END { for (key in count) print count[key], key }' "$LOG_FILE" | sort -nr
