#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 
count=1

while [ $count -le 20 ]
do
  case $count in
    4)
      echo "4"
      echo "Bad luck from China"
      ;;
    9)
      echo "9"
      echo "Bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "Bad luck from Italy"
      ;;
    *)
      echo $count
      ;;
  esac

  count=$((count + 1))
done
