#!/usr/bin/env bash
#Bash script that displays a list of currently running processes
processes=$(ps -eo pid,ppid,user,cmd --forest)
printf "%-7s %-7s %-15s %s\n" "PID" "PPID" "USER" "COMMAND"
while IFS= read -r process; do
  pid=$(echo "$process" | awk '{print $1}')
  ppid=$(echo "$process" | awk '{print $2}')
  user=$(echo "$process" | awk '{print $3}')
  command=$(echo "$process" | awk '{print $4}')
printf "%-7s %-7s %-15s %s\n" "$pid" "$ppid" "$user" "$command"
done <<< "$processes"
